steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        echo "📂 Isi folder saat build:"
        ls -la
        gcloud app deploy app.yaml --quiet
    dir: "."
