steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - app
      - deploy
      - app.yaml
      - "--quiet"
    dir: "."  # Gunakan root folder karena app.yaml dan index.html ada di sana

options:
  logging: CLOUD_LOGGING_ONLY

